### ISSUE TITLE
0.7.0 breaking changes - compatibility tracking issue

### ISSUE THREAD

**Issue by federicobond** [open-feature/python-sdk#319]
With 0.7.0, we are taking a more strict approach to exporting names in our public API. In https://github.com/open-feature/python-sdk/pull/306 we began using `__all__` inside each package to explicitly declare the names that are exported from it, thus enforcing a canonical import path for each class/function.

**Package maintainers:** if you were previously importing names from non-canonical locations, you will need to update your imports to point to the canonical ones. Your code should then be able to work with both current and 0.7.0 SDK versions.

If you have any other questions, feel free to leave a comment here.

### Packages that may need updating

 * [ ] https://pypi.org/project/cloudbees-openfeature-provider-python/
 * [ ] https://pypi.org/project/split-openfeature/
 * [ ] https://pypi.org/project/confidence-openfeature-provider/
 * [ ] https://pypi.org/project/launchdarkly-openfeature-server/
 * [ ] https://pypi.org/project/openfeature-provider-flagsmith/
 * [ ] https://pypi.org/project/gofeatureflag-python-provider/
 * [ ] https://github.com/DevCycleHQ/python-server-sdk

**Comment by federicobond** [comment]
tagging @AsafRollout @rgrassian-split @nicklasl @keelerm84 @matthewelwell @thomaspoignant @chris-hoefgen

**Comment by nicklasl** [comment]
Thanks for the ping @federicobond 👍

**Comment by thomaspoignant** [comment]
@federicobond thanks for the heads up, do you have any example of what tondo by any chance?

**Comment by beeme1mr** [comment]
@jonathannorris FYI

**Comment by thomaspoignant** [comment]
It should be ok for GO Feature Flag, waiting for the SDK to be released to release the new version of the provider.

**Comment by thomaspoignant** [comment]
@federicobond do you know when v0.7.0 will be released?

**Comment by federicobond** [comment]
Thanks for the heads up. I just cut the 0.7.0 release! 🎉

**Comment by gruebel** [comment]
I checked and all listed 3rd party providers support SDK 0.8 or higher
