### ISSUE TITLE
Update SDK to be compliant with spec v0.2.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/python-sdk#7]
Update the SDK to be compliant with the v0.2.0 spec.

## Flag Evaluation API
- [ ]  [#116](https://github.com/open-feature/spec/pull/116) - Have different methods for float and int

## Providers
- [ ]  [#119](https://github.com/open-feature/spec/pull/119) - Remove context transformers. Add provider hooks

## Evaluation Context
- [ ]  [#117](https://github.com/open-feature/spec/pull/117) - Ensure context merging behavior is correct
- [ ]  [#120](https://github.com/open-feature/spec/pull/120) - Add the ability to fetch all custom fields
- [ ]  [#121](https://github.com/open-feature/spec/pull/121) - Ensure evaluation context keys are unique

## Hooks
- [ ]  [#119](https://github.com/open-feature/spec/pull/119) - Ensure provider hook are correctly ordered

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.1.0...v0.2.0

**Comment by mschoenlaub** [comment]
@beeme1mr Not sure, but "Add the ability to fetch all custom fields" and "Ensure evaluation context keys are unique" are solved implicitly. One could access `ctx.attributes` and the fact that they are a `dict` should solve the uniqueness. Agreed?

**Comment by beeme1mr** [comment]
Yes, I agree those requirements would be addressed implicitly with a dictionary.
